#!/bin/bash
set -e

gh_owner=bitcoin
gh_repo=bitcoin

case $(uname -m) in
  armv7l) arch="arm";;
  x86_64) arch="x86_64";;
  *) echo "Architecture $ARCH not supported by the installation script"; exit 1;;
esac

latest_version=$(wget -qO- https://api.github.com/repos/$gh_owner/$gh_repo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed -E 's/v//')
build=bitcoin-$latest_version-x86_64-linux-gnu.tar.gz

wget -qO- https://bitcoin.org/bin/bitcoin-core-${latest_version}/$build | tar -xvz -C /tmp

mv /tmp/bitcoin-$latest_version/bin/bitcoind /
mv /tmp/bitcoin-$latest_version/bin/bitcoin-cli /