#!/bin/bash
set -e

gh_owner=OmniLayer
gh_repo=omnicore

case $(uname -m) in
  armv7l) arch="arm";;
  x86_64) arch="x86_64";;
  *) echo "Architecture $ARCH not supported by the installation script"; exit 1;;
esac

latest_version=$(wget -qO- https://api.github.com/repos/$gh_owner/$gh_repo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed -E 's/v//')
build=omnicore-$latest_version-x86_64-linux-gnu.tar.gz
echo $build
echo https://github.com/$gh_owner/$gh_repo/releases/download/${latest_version}/$build

wget -qO- https://github.com/$gh_owner/$gh_repo/releases/download/v${latest_version}/$build | tar -xvz -C /tmp

mv /tmp/omnicore-$latest_version/bin/omnicored /
mv /tmp/omnicore-$latest_version/bin/omnicore-cli /
